trigger:
  branches:
    include:
    - master
    - release/*

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Building the application...
      displayName: 'Build'

- stage: DeployToDev
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying to development environment...
            displayName: 'Deploy Dev'

- stage: DeployToQA
  dependsOn: DeployToDev
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'qa'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying to QA environment...
            displayName: 'Deploy into QA'
